name: date_time_picker_widget
description: This package brings us a way to pick date and time with fresh new UI design
version: 2.0.0
homepage: https://github.com/mikes222/date_time_picker_widget

environment:
  sdk: '>=2.12.0 <3.0.0'
  #flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  stacked: ^3.4.0
  jiffy: ^6.2.1
  scrollable_positioned_list: ^0.3.8
  rxdart: ^0.27.7
  golden_toolkit: ^0.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

